# Default values for ack-tensorflow-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jupyter:
  image:
    repository: twobombs/thereminq-tensors
    tag: latest
    pullPolicy: Always
  password: tensorflow
  resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #  nvidia.com/gpu: 1
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  #  nvidia.com/gpu: 1
tensorboard:
  image:
    repository: twobombs/thereminq-tensors
    tag: latest
    pullPolicy: Always
service:
  type: LoadBalancer
