apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "template.fullname" . }}
spec:
  rules:
  - host: ingress-{{ include "template.fullname" . }}.ddns.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "template.fullname" . }}
            port:
              number: 6080
